CREATE TABLE developers (
    ID 			    INT	NOT NULL AUTO_INCREMENT,
	NAME		    VARCHAR(200)	NOT NULL,
    GAMES_COUNT     INT NOT NULL,
	BACKGROUND_IMAGE VARCHAR(250) NOT NULL,

	PRIMARY KEY (ID)
);


