CREATE TABLE game (
    ID 			    INT	NOT NULL AUTO_INCREMENT,
	NAME		    VARCHAR(200)	NOT NULL,
	RELEASED        VARCHAR(50) NOT NULL,
	RATING        VARCHAR(50) NOT NULL,
	BACKGROUND_IMAGE VARCHAR(250) NOT NULL,
	GENERES     VARCHAR(250) NOT NULL,
	PRIMARY KEY (ID)
);


